/**
 * PeerID.js
 *
 * This module generates a unique peer ID based on the peer's IP address and port number.
 * The peer ID is generated by using the Blake2s256 hashing algorithm to produce a hash
 * of the input string "IP:port". The first 4 hex characters of the hash (16 bits) are used
 * as the peer ID.
 */

const crypto = require("crypto");

function getPeerID(ip, port) {
  // Concatenate the IP address and port number to form a unique input string.
  const input = `${ip}:${port}`;

  // Create a Blake2s256 hash of the input.
  // Note: Make sure your Node.js version supports 'blake2s256'
  const hash = crypto.createHash("blake2s256").update(input).digest("hex");

  // Extract the first 4 hex characters (16 bits) as the peer ID.
  return hash.slice(0, 4);
}

module.exports = {
  getPeerID,
};
